In [304]:
import pymysql
import pandas as pd
import numpy as np
import re
from scipy.stats import pearsonr
from tqdm import tqdm

In [305]:
try:
    conn_=pymysql.connect(
                        host='khk.cepsu2i8bkn5.ap-northeast-2.rds.amazonaws.com',
                        user='khk',
                        password='k2hyokwang2!',
                        charset='utf8mb4',
                        cursorclass=pymysql.cursors.DictCursor,
                        port=3306,
                        db='information_schema'
    )

    with conn_.cursor() as cursor:
        sql='SELECT TABLE_NAME FROM TABLES WHERE TABLES.TABLE_SCHEMA="hist_data";'
        cursor.execute(sql)
        rows=cursor.fetchall()
    
except Exception as e:
    print(e)
finally:
    conn_.close()

In [306]:
def hist_data(code):
    try:
        conn_=pymysql.connect(
        host='khk.cepsu2i8bkn5.ap-northeast-2.rds.amazonaws.com',
        user='khk',
        password='k2hyokwang2!',
        charset='utf8mb4',
        cursorclass=pymysql.cursors.DictCursor,
        port=3306,
        db='hist_data'
        )

        with conn_.cursor() as cursor:
            sql=f'SELECT * FROM `{code}`;'
            cursor.execute(sql)
            db_table=cursor.fetchall()
            data=pd.DataFrame(db_table)

    except  Exception as e:
        print(e)
    finally:
        conn_.close()
        data.index=data['날짜']
        del data['날짜']
        data=data[['종가']]
        data['종가']=data['종가'].apply(lambda x: re.sub(',','',x))
        data=data.astype(np.float64)
        data['수익률']=round(data['종가']/data['종가'].shift(1)-1,4)
        data=data.iloc[1:,:]['수익률']
    return data

In [307]:
def get_corr(hist1,hist2):
    data1=hist_data(hist1)
    data2=hist_data(hist2)
    data=pd.merge(data1,data2,how='inner',left_index=True,right_index=True)
    data.columns=[hist1,hist2]
    data=data.fillna(0)
    r=data.corr(method='pearson')
    r=r.iloc[0,1]
    r=round(r,4)
    return r

In [311]:
conn_=''
try:
    conn_=pymysql.connect(
                        host='khk.cepsu2i8bkn5.ap-northeast-2.rds.amazonaws.com',
                        user='khk',
                        password='k2hyokwang2!',
                        charset='utf8mb4',
                        cursorclass=pymysql.cursors.DictCursor,
                        port=3306,
                        db='scrap_data'
    )

    with conn_.cursor() as cursor:
        sql='SELECT 종목코드 FROM 코스피상장기업;'
        cursor.execute(sql)
        rows_=cursor.fetchall()
    
except Exception as e:
    print(e)
finally:
    conn_.close()

In [313]:
corp_code=[x.get('종목코드') for x in rows_]

matx_frame=np.zeros(len(corp_code)**2).reshape(len(corp_code),len(corp_code))
matx=pd.DataFrame(matx_frame,index=corp_code,columns=corp_code)
# matx=matx.iloc[:10,:10]
matx=matx.astype(np.float)
matx

,352820,363280,357120,348950,357250,350520,334890,326030,353200,344820,...,000240,000950,003490,001530,000100,000120,000060,000050,000700,003480
352820,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
363280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
357120,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
348950,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
357250,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
000120,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000060,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000050,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
000700,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
003480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
for n,i in enumerate(matx.index):
    for j in tqdm(matx.columns[n:]):
        matx.loc[i,j]=get_corr(i,j)
for n,i in tqdm(enumerate(matx.columns)):
    for j in tqdm(matx.index[n:]):
        matx.loc[j,i]=matx.loc[i,j]

100%|████████████████████████████████████████████████████████████████████████████████| 797/797 [05:42<00:00,  2.33it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 796/796 [05:28<00:00,  2.43it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 795/795 [05:34<00:00,  2.37it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 794/794 [05:30<00:00,  2.40it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 793/793 [05:42<00:00,  2.32it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 792/792 [05:38<00:00,  2.34it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 791/791 [05:33<00:00,  2.37it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 790/790 [05:53<00:00,  2.23it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 789/789 [06:38<00:00,  1.98it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 788/788 [06:43<00:00,  1.95it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 787/787 [06:44<00:00,  1.94it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 786/786 [07:33<00:00,  1.73it/s]
 75%|████████████████████████████████████████████████████████████▏                   | 590/785 [05:00<01:56,  1.67it/s]

In [296]:
matx

,196300,171010,006650,192390,270870,003080,030960,071670,100120,004840
196300,1.0000,0.1451,0.1384,0.1985,0.3105,0.1625,0.0887,0.2139,0.2681,0.1844
171010,0.1451,1.0000,0.0792,0.0989,0.1460,0.0673,0.0711,0.1151,0.1463,0.1280
006650,0.1384,0.0792,1.0000,0.1897,0.3030,0.1111,0.1156,0.1739,0.1938,0.1295
192390,0.1985,0.0989,0.1897,1.0000,0.2882,0.0728,0.1549,0.1895,0.2268,0.2164
270870,0.3105,0.1460,0.3030,0.2882,1.0000,0.2340,0.1866,0.2618,0.3222,0.1789
003080,0.1625,0.0673,0.1111,0.0728,0.2340,1.0000,0.0737,0.0791,0.0861,0.1604
030960,0.0887,0.0711,0.1156,0.1549,0.1866,0.0737,1.0000,0.0833,0.1027,0.0560
071670,0.2139,0.1151,0.1739,0.1895,0.2618,0.0791,0.0833,1.0000,0.2540,0.1671
100120,0.2681,0.1463,0.1938,0.2268,0.3222,0.0861,0.1027,0.2540,1.0000,0.1325
004840,0.1844,0.1280,0.1295,0.2164,0.1789,0.1604,0.0560,0.1671,0.1325,1.0000

In [297]:
matx.to_pickle('corr_matrix.pkl')

In [174]:
data=pd.read_pickle('corr_matrix.pkl')
data

,196300,171010,006650,192390,270870,003080,030960,071670,100120,004840
196300,1.0000,0.1451,0.1384,0.1985,0.3105,0.1625,0.0887,0.2139,0.2681,0.1844
171010,0.1451,1.0000,0.0792,0.0989,0.1460,0.0673,0.0711,0.1151,0.1463,0.1280
006650,0.1384,0.0792,1.0000,0.1897,0.3030,0.1111,0.1156,0.1739,0.1938,0.1295
192390,0.1985,0.0989,0.1897,1.0000,0.2882,0.0728,0.1549,0.1895,0.2268,0.2164
270870,0.3105,0.1460,0.3030,0.2882,1.0000,0.2340,0.1866,0.2618,0.3222,0.1789
003080,0.1625,0.0673,0.1111,0.0728,0.2340,1.0000,0.0737,0.0791,0.0861,0.1604
030960,0.0887,0.0711,0.1156,0.1549,0.1866,0.0737,1.0000,0.0833,0.1027,0.0560
071670,0.2139,0.1151,0.1739,0.1895,0.2618,0.0791,0.0833,1.0000,0.2540,0.1671
100120,0.2681,0.1463,0.1938,0.2268,0.3222,0.0861,0.1027,0.2540,1.0000,0.1325
004840,0.1844,0.1280,0.1295,0.2164,0.1789,0.1604,0.0560,0.1671,0.1325,1.0000

        196300  171010  006650  192390  270870
196300  1.0000  0.1451  0.1384  0.1985  0.3105
171010  0.1451  1.0000  0.0792  0.0989  0.1460
006650  0.1384  0.0792  1.0000  0.1897  0.3030
192390  0.1985  0.0989  0.1897  1.0000  0.2882
270870  0.3105  0.1460  0.3030  0.2882  1.0000

dtype('float64')

array([ 0.0314, -0.0045, -0.0045, -0.0261,  0.0245, -0.0137, -0.0346,
       -0.0443, -0.015 ,  0.0407, -0.0159,  0.0136, -0.0159,  0.0075,
        0.    ,  0.0247, -0.0217,  0.0259, -0.0036,  0.    , -0.0072,
        0.0194,  0.0048,  0.0166,  0.0455,  0.0056, -0.0033, -0.0189,
       -0.0147, -0.0127, -0.0035,  0.0246,  0.0274, -0.0044,  0.0491,
        0.0436,  0.001 , -0.0468,  0.0256, -0.0083, -0.0242,  0.0205,
        0.0232, -0.0278, -0.0074, -0.016 ,  0.0098, -0.0183, -0.0055,
       -0.0066, -0.0033,  0.0011,  0.    , -0.0089, -0.0224, -0.0206,
       -0.0012,  0.0082, -0.0058,  0.0082, -0.0035,  0.0058, -0.0012,
       -0.0046, -0.0081, -0.0082,  0.0012,  0.0047,  0.0353,  0.    ,
       -0.025 ,  0.0047,  0.0046, -0.0092,  0.0221,  0.049 ,  0.0315,
       -0.0021,  0.    , -0.0011, -0.0042, -0.0021, -0.0032, -0.0149,
       -0.0184,  0.0077,  0.0011,  0.0011,  0.0033, -0.0022,  0.0044,
       -0.0217, -0.0156, -0.0192, -0.0035, -0.0035,  0.    ,  0.    ,
       -0.0336, -0.0024,  0.    , -0.0096, -0.0376,  0.005 , -0.0201,
        0.1012, -0.0884, -0.0179,  0.0169,  0.0179, -0.0025, -0.0088,
       -0.0076,  0.0077,  0.    ,  0.0025, -0.0076,  0.    ,  0.0013,
       -0.0013,  0.0064, -0.0139,  0.0206, -0.0088, -0.0064,  0.0026,
        0.0204,  0.075 ,  0.    ,  0.0256,  0.0204,  0.0256,  0.0823,
       -0.001 , -0.007 ,  0.001 , -0.002 , -0.0101, -0.0173, -0.0239,
        0.    , -0.0085,  0.0418, -0.0175,  0.0021, -0.0377,  0.0293,
        0.0011,  0.0063, -0.0105, -0.0021, -0.0011, -0.0255, -0.0174,
       -0.01  , -0.0011,  0.0281, -0.024 , -0.0112, -0.009 , -0.0148,
        0.0162,  0.0011, -0.0057, -0.0034,  0.0092,  0.008 , -0.0011,
        0.    , -0.0136, -0.008 , -0.022 , -0.0142,  0.    , -0.0168,
        0.0122,  0.006 , -0.0132, -0.0182,  0.0309,  0.018 ,  0.0106,
       -0.0047, -0.0164,  0.0024,  0.0059, -0.013 ,  0.012 , -0.0035,
       -0.0119, -0.006 ,  0.006 , -0.0072,  0.    ,  0.0145, -0.0274,
       -0.0049, -0.0099,  0.0062,  0.0087, -0.0025,  0.    , -0.0049,
        0.0111, -0.0037, -0.0159, -0.005 ,  0.0013, -0.0125, -0.0076,
        0.0166, -0.0038,  0.    , -0.0025, -0.0051, -0.0063, -0.0038,
        0.0231,  0.    , -0.005 , -0.0227,  0.    , -0.0064, -0.0039,
        0.0039,  0.0065,  0.0077,  0.023 ,  0.0012,  0.0012, -0.0037,
        0.    , -0.0213, -0.0102, -0.0013,  0.0039,  0.018 ,  0.0152,
        0.0848,  0.0241, -0.0011, -0.0045, -0.0293,  0.0035,  0.0081,
        0.0069,  0.0023, -0.0034, -0.0343, -0.0036, -0.0024, -0.0048,
       -0.0048,  0.0144,  0.0024, -0.0118, -0.0096, -0.0036,  0.0012,
       -0.0061,  0.011 ,  0.    , -0.0108, -0.0134, -0.0086, -0.0037,
       -0.005 , -0.0088, -0.0038,  0.0038, -0.0114, -0.0154, -0.0182,
        0.0186,  0.0117,  0.0167,  0.0038,  0.0013,  0.    , -0.0239,
        0.    , -0.0052, -0.0091,  0.0131,  0.0026,  0.0039,  0.027 ,
        0.0137, -0.0136,  0.0137, -0.0062,  0.0012, -0.0012,  0.0124,
       -0.0049, -0.0012,  0.0148,  0.0073, -0.0109, -0.0061,  0.0429,
        0.1   ,  0.0503,  0.0071, -0.0111,  0.0051, -0.0397,  0.0265,
        0.0402,  0.254 , -0.0886,  0.0122, -0.0669, -0.0074, -0.0093,
       -0.0075, -0.0226,  0.    , -0.0116, -0.0117, -0.0039, -0.0238,
       -0.0223, -0.027 ,  0.0309,  0.0083, -0.0154,  0.0042,  0.0093,
       -0.0195,  0.0189,  0.0237, -0.0201,  0.0031, -0.0092, -0.0052,
        0.0197,  0.058 ,  0.0058, -0.021 , -0.0156, -0.004 , -0.005 ,
       -0.025 , -0.0216,  0.0042,  0.0199,  0.0195, -0.001 , -0.0312,
       -0.0031,  0.0073,  0.0052, -0.0237,  0.02  ,  0.2087, -0.0034,
       -0.0223,  0.    , -0.0018, -0.0545,  0.0074, -0.0683,  0.0218,
        0.    , -0.0194,  0.0059,  0.0098, -0.034 , -0.0302, -0.0031,
       -0.0104,  0.0011, -0.0179, -0.0086,  0.0011,  0.0119, -0.0011,
       -0.0117, -0.0119, -0.0175, -0.0022,  0.0011, -0.0122, -0.0045,
       -0.0125,  0.0206, -0.0225, -0.0092,  0.036 , -0.019 ,  0.0068,
       -0.0079, -0.0023, -0.0183, -0.007 , -0.0106, -0.0166,  0.    ,
        0.0169,  0.0024,  0.0012, -0.0059,  0.0024,  0.0012, -0.0012,
        0.0012,  0.    , -0.0047,  0.    , -0.0048, -0.0012,  0.0084,
       -0.0048, -0.0203,  0.0012,  0.0012, -0.0061,  0.0012, -0.0024,
        0.0245, -0.0024,  0.0108,  0.    , -0.0071, -0.0119,  0.0024,
       -0.0157,  0.    ,  0.0012, -0.0012, -0.0074,  0.0025, -0.0135,
        0.    ,  0.    , -0.0075, -0.0201, -0.0205, -0.0249,  0.0363,
       -0.0233,  0.0584, -0.0088, -0.0063, -0.0102, -0.0026, -0.0258,
        0.0331, -0.0013,  0.0039,  0.0179,  0.0025, -0.0201, -0.0243,
        0.0039, -0.0078,  0.    ,  0.    , -0.0368,  0.015 ,  0.0121,
        0.0053, -0.0132,  0.0188, -0.0184,  0.0054, -0.0133,  0.    ,
       -0.0041,  0.0095, -0.0228,  0.    , -0.0041,  0.0083, -0.0411,
        0.01  , -0.0141, -0.0086, -0.0159,  0.    ,  0.0132,  0.0174,
        0.0128,  0.0155, -0.025 , -0.0199, -0.0363,  0.009 ,  0.0075,
       -0.0044,  0.0253, -0.0087, -0.0176,  0.0119, -0.0398, -0.0399,
       -0.0128, -0.0032, -0.0114, -0.0099, -0.0216,  0.0508,  0.0048,
        0.0128, -0.019 , -0.0097,  0.031 ,  0.019 ,  0.0047,  0.0093,
       -0.0092,  0.0031, -0.0046, -0.0186,  0.0095,  0.0625,  0.0103,
        0.    ,  0.0058,  0.0275, -0.0056, -0.0042,  0.0014,  0.0043,
       -0.0014,  0.0057,  0.0085,  0.0014, -0.0014,  0.007 ,  0.0555,
        0.0355,  0.0063,  0.0113, -0.0025, -0.0025, -0.0138,  0.0089,
       -0.0113,  0.0115, -0.0202, -0.0103,  0.0221, -0.0089,  0.0038,
        0.0051,  0.0013,  0.    ,  0.    ,  0.0013, -0.0063,  0.023 ,
       -0.0025,  0.005 , -0.0249,  0.0536, -0.0351,  0.0063,  0.0187,
       -0.0073,  0.0185, -0.0097,  0.0024, -0.0171,  0.0062,  0.0111,
       -0.0159,  0.0012,  0.0025,  0.0049,  0.    ,  0.    , -0.0184,
        0.02  , -0.0012,  0.0037, -0.0061, -0.0049, -0.0025, -0.0087,
       -0.0038,  0.0063, -0.0025,  0.005 ,  0.    ,  0.0012,  0.    ,
        0.0037, -0.0025, -0.0087,  0.0163,  0.0099,  0.    ,  0.0061,
        0.    , -0.0061, -0.011 , -0.0123, -0.0038, -0.0013, -0.0038,
        0.0013,  0.    ,  0.0139, -0.0062,  0.0025, -0.01  ,  0.0076,
       -0.0088, -0.0038,  0.0076, -0.0038,  0.0088, -0.015 , -0.014 ,
       -0.0077,  0.0091,  0.0039,  0.0115, -0.0127,  0.    , -0.0013,
       -0.0308,  0.1377,  0.2992,  0.1631, -0.0416, -0.0707,  0.0692,
       -0.11  ,  0.0109, -0.0216,  0.0846,  0.1966, -0.0382, -0.0044,
       -0.0178, -0.0904,  0.1358, -0.0671, -0.0531,  0.0198,  0.0275,
        0.2992, -0.0594, -0.1134,  0.2355,  0.0118,  0.0442, -0.108 ,
        0.0362, -0.0133, -0.0513,  0.0039, -0.0141,  0.0754, -0.0314,
       -0.0387, -0.0597, -0.0124, -0.0601,  0.0387,  0.0501,  0.0177,
       -0.0228, -0.0672, -0.0618,  0.0204, -0.0092,  0.1225,  0.0069,
       -0.0288, -0.0169, -0.0144,  0.019 , -0.03  , -0.0103,  0.0015,
        0.0164,  0.0044, -0.0525,  0.0031, -0.0475,  0.0338,  0.0171,
       -0.0337,  0.0491,  0.0453,  0.2991,  0.0278,  0.0639,  0.001 ,
       -0.0346, -0.0358, -0.0011, -0.0219, -0.0302, -0.015 , -0.0363,
        0.0243, -0.0521,  0.0137,  0.0062, -0.0527, -0.0065,  0.0026,
        0.0195,  0.0191, -0.0463,  0.0079,  0.    , -0.0455, -0.0041,
        0.0164,  0.0431, -0.0026,  0.0129,  0.0153, -0.044 , -0.0092,
       -0.0345, -0.011 ,  0.0362, -0.0148,  0.0259,  0.0027, -0.0053,
       -0.008 ,  0.0121, -0.0053,  0.0173, -0.0485,  0.0165,  0.0122,
        0.0013,  0.0187,  0.0092, -0.0065,  0.0079,  0.0779, -0.0325,
        0.01  , -0.0037, -0.0594, -0.0184,  0.0107,  0.0265, -0.009 ,
        0.0052,  0.0545,  0.0135, -0.0255, -0.0623,  0.0398,  0.0064,
        0.0025,  0.0025, -0.0038, -0.0101,  0.0205, -0.0213, -0.0192,
        0.0092, -0.0013, -0.0532, -0.0055, -0.0193, -0.0744,  0.0622,
        0.0057,  0.0043,  0.0311,  0.0137, -0.0081,  0.0055,  0.0312,
       -0.0263, -0.0081,  0.015 , -0.0161, -0.0246, -0.0028, -0.0435,
       -0.0543,  0.0388, -0.0388, -0.0528, -0.0492,  0.0638, -0.0227,
        0.0232,  0.0113, -0.016 , -0.0782,  0.0124, -0.0663, -0.0701,
       -0.1136, -0.0374,  0.0024, -0.0776, -0.2408,  0.1007, -0.0427,
        0.1465,  0.0556,  0.1513,  0.0366,  0.0805,  0.002 , -0.0214,
        0.0198, -0.0102,  0.0557,  0.0547,  0.063 ,  0.007 , -0.0138,
       -0.0649,  0.0356,  0.0326,  0.0123, -0.0104, -0.021 , -0.0072,
        0.009 , -0.0321,  0.0166, -0.0127,  0.0129, -0.0036,  0.0091,
        0.0812,  0.02  , -0.0262, -0.0118, -0.0017, -0.0068, -0.0051,
        0.019 ,  0.0203,  0.1194, -0.0119,  0.006 ,  0.0089,  0.0192,
       -0.0261, -0.0402, -0.0186,  0.0806, -0.0029,  0.0044,  0.0569,
        0.0953,  0.0063, -0.0226, -0.0359, -0.0279, -0.0219, -0.1035,
        0.0265,  0.0167,  0.0239,  0.092 , -0.004 , -0.0228,  0.0412,
        0.0198, -0.0233, -0.0265,  0.0558, -0.0245,  0.0119, -0.0078,
       -0.0158, -0.0174,  0.0231,  0.012 , -0.0158,  0.0107, -0.0132,
        0.0228,  0.0733, -0.0341, -0.024 ,  0.0052, -0.0257,  0.    ,
       -0.0291,  0.0735, -0.0139,  0.0013,  0.0282, -0.0225,  0.037 ,
       -0.0209, -0.0013,  0.0542, -0.0287, -0.0025, -0.0037, -0.0334,
        0.    , -0.0154, -0.104 , -0.0087, -0.0512,  0.0154,  0.0304,
        0.0103,  0.0029, -0.032 ,  0.0271, -0.0176,  0.0253,  0.0029,
        0.0696, -0.0244,  0.0069, -0.0028, -0.0124,  0.0126, -0.0055,
        0.0097, -0.0028, -0.0138, -0.021 , -0.0129, -0.0159, -0.0295,
        0.0197, -0.0327, -0.0138,  0.0218,  0.0031,  0.0076,  0.0151,
        0.0015, -0.0104,  0.    , -0.003 , -0.006 , -0.0227,  0.    ,
       -0.0093, -0.0313,  0.0097, -0.0032, -0.008 , -0.0405,  0.0371,
       -0.0033, -0.0131, -0.0182, -0.0017,  0.0118,  0.01  ,  0.0281,
       -0.0177,  0.0082, -0.0032,  0.0098,  0.0032,  0.    ,  0.0257,
       -0.0125,  0.0048, -0.0142,  0.0144, -0.0047,  0.019 , -0.028 ,
       -0.0048,  0.119 , -0.0029,  0.0101,  0.    ,  0.0029, -0.0142,
       -0.0216, -0.0103,  0.0134, -0.0029,  0.    , -0.0088, -0.0134,
        0.0181,  0.0193,  0.    , -0.0116, -0.0309,  0.0046,  0.003 ])